referecnes:
  defaults: &defaults
    docker:
      - image: node:8.9.4
    working_directory: ~/oneteam-dev/draft-js-oneteam-rte-plugin
    environment:
      TZ: '/usr/share/zoneinfo/UTC'
  restore_git_cache: &restore_git_cache
    keys:
      - draft-js-oneteam-rte-plugin-git-v1-{{ .Branch }}-
  save_git_cache: &save_git_cache
    key: draft-js-oneteam-rte-plugin-git-v1-{{ .Branch }}-
    paths:
      - ~/.gitconfig
  restore_yarn_cache: &restore_yarn_cache
    keys:
      - draft-js-oneteam-rte-plugin-yarn-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - draft-js-oneteam-rte-plugin-yarn-v1-{{ .Branch }}-
  save_yarn_cache: &save_yarn_cache
    key: draft-js-oneteam-rte-plugin-yarn-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
    paths:
      - ~/.cache/yarn
      - ./node_modules

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore_git_cache
      - run:
          name: Setting git config
          command: |
            git config --global user.name 'Circle CI'
            git config --global user.email 'a+circleci@ngs.io'
      - save_cache: *save_git_cache
      - restore_cache: *restore_yarn_cache
      - run: yarn
      - save_cache: *save_yarn_cache
      - store_artifacts:
          path: npm-debug.log
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore_git_cache
      - restore_cache: *restore_yarn_cache
      - run: npm test
      - run: npm run eslint -- --max-warnings 0
      - run: npm run flow
      - run: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
      - run: cp -R coverage $CIRCLE_ARTIFACTS/
      - run: mkdir -p $CIRCLE_TEST_REPORTS/nyc && cp test-results.xml $CIRCLE_TEST_REPORTS/nyc
      - store_artifacts:
          path: npm-debug.log
  deploy:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore_git_cache
      - restore_cache: *restore_yarn_cache
      - run: npm run build:demo
      - run: npm run deploy:demo
      - store_artifacts:
          path: npm-debug.log

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
      - test:
          filters:
            branches:
              ignore:
                - gh-pages
          requires:
            - build
      - deploy:
          filters:
            branches:
              only: /master|deploy-.+/
          requires:
            - test
